### ISSUE TITLE
Interoperability between Lua and Python coroutines in Python 3.5+

### ISSUE THREAD

**Issue by sparkyb** [scoder/lupa#125] opened 2019-10-10 19:59 UTC
Now that Python has proper coroutines in Python 3.5+, it would be nice for Lua coroutines to be able to function as Python coroutines and vice versa so that Lua could be used with something like asyncio. Right now a Lua coroutine functions like a Python generator (has a .send() method), but not a Python coroutine. It is not even wrappable into a Python coroutine with types.coroutine() because it doesn't fit the full signature of a Python generator since it is missing .throw() and .close(). Additionally, it would be nice if Python coroutines could be passed to Lua as a Lua coroutine so that they could be resumed with coroutine.resume().

**Comment by SoulSen** [comment] 2019-12-26 23:15
If I'm understanding what you are asking of, this is similar to my issue of #120 and since @scoder has told me that it won't be fixed since it's not a Lupa problem. I have created a separate module that serves this purpose which is [AsyncLupa](https://github.com/SoulSen/AsyncLupa), if you are interested.

**Comment by scoder** [comment] 2020-01-04 09:11
Closing as duplicate of #120.

As long as there is no Obvious Right Way to integrate the two, I think it's better left to user code or third-party extensions than to Lupa itself.

**Closed by scoder** 2020-01-04 09:11 UTC
