### ISSUE TITLE
require does not seem to handle nested modules

### ISSUE THREAD

**Issue by whitelizard** [scoder/lupa#201] opened 2022-01-07 18:46 UTC
I'm trying to import a module that in turn uses require to import utils. It works fine in lua interpreter, but not with lua.require('X'). Is this possible? What should I do to get that module into my lupa environment?

**Comment by scoder** [comment] 2022-01-09 09:18
What is failing? In what way? Is it not finding the module? Maybe a search path issue?

**Comment by whitelizard** [comment] 2022-01-10 09:39
The module I'm trying to import is [rFSM](https://github.com/kmarkus/rFSM)

It seems that the external module's own relative imports does not work. I get this error:
`rfsm.lua:9: module 'utils' not found`

It sais that it is looking in `'./utils.lua'` but I guess that it is relative to where my script is running, the parent folder?
If I add the correct external module path to Lua, `LUA_PATH=";;;/home/ez/dev/rFSM-master/?.lua"`, it is indeed solved. But...

Then I get this error:
`utils.lua:9: global 'module' is not callable (a nil value)`
which I can not get around.

Is the keyword `module` not supported by lupa?

**Comment by whitelizard** [comment] 2022-01-12 09:16
This issue is perhaps not titled correctly now, but what would be a better title? Should I create a new issue?

**Comment by scoder** [comment] 2022-01-12 09:50
Let's keep the discussion in this ticket until we know at least whether there is something to do in Lupa.

Would it help if the `LuaRuntime` provided a way to configure Lua's module search path? Or is that easy enough to do from within Lua?

I don't know what `module` is in Lua (probably not a keyword if it tries to call it), and it's a generic name that is difficult to search for. I have no idea why it shouldn't work in Lua. Could you provide some details here?

**Comment by whitelizard** [comment] 2022-01-12 11:04
It would certainly help if paths could be given programmatically instead of only environment-wise, yes.

It can be seen in that [utils.lua](https://github.com/kmarkus/rFSM/blob/master/utils.lua) file, how `module` is used.
It is also used in the library main file, [rfsm.lua](https://github.com/kmarkus/rFSM/blob/master/rfsm.lua).

In the [modules section](https://www.lua.org/manual/5.1/manual.html#5.3) in Lua documentation, the Lua module syntax is described.

Do you need anything more?

**Comment by scoder** [comment] 2022-01-12 12:47
It seems that that function is gone in later Lua versions:
https://www.lua.org/manual/5.4/manual.html#6.3

**Comment by scoder** [comment] 2022-01-12 12:51
You can see the Lua version that Lupa is using in `lupa.LUA_VERSION`. Should be 5.4 for the current binary wheels and the default build.

**Comment by whitelizard** [comment] 2022-01-19 09:01
Ok so, yes, it was a version mismatch. It was a very hard problem of trying to match versions that I in the end could not solve. My situation is that I, through lupa, am running a Lua sandbox that should have rFSM imported beforehand, and then be able to run custom Lua scripts. But despite the docs for the sandbox it did not support Lua 5.1 that is needed for rFSM. But thanks for the answers here!

**Comment by scoder** [comment] 2022-01-19 15:11
Ok. Closing as "not a bug".

**Closed by scoder** 2022-01-19 15:11 UTC
Labels: support question
