### ISSUE TITLE
pip install lupa fails on Windows

### ISSUE THREAD

**Issue by peso** [scoder/lupa#257] opened 2024-02-18 21:45 UTC
I'm trying pip install lupa with Python 3.12.0 on Windows 11, but it fails with this error message:
I have replaced user specific paths with %TEMP% and %PYVENV%

```
>pip install lupa
Collecting lupa
  Using cached lupa-2.0.tar.gz (6.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [61 lines of output]
      %TEMP%\pip-build-env-c8dy9cop\overlay\Lib\site-packages\setuptools\_distutils\dist.py:265: UserWarning: Unknown distribution option: 'build_requires'
        warnings.warn(msg)
      Using bundled Lua in lua52
      Using bundled Lua in lua53
      Using bundled Lua in lua54
      generated sources not available, need Cython to build
      WARNING: trying to build with Cython, but it is not installed
      running egg_info
      writing lupa.egg-info\PKG-INFO
      writing dependency_links to lupa.egg-info\dependency_links.txt
      writing top-level names to lupa.egg-info\top_level.txt
      reading manifest file 'lupa.egg-info\SOURCES.txt'
      Traceback (most recent call last):
        File "%PYVENV%\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "%PYVENV%\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "%PYVENV%\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "%TEMP%\pip-build-env-c8dy9cop\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "%TEMP%\pip-build-env-c8dy9cop\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "%TEMP%\pip-build-env-c8dy9cop\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super().run_setup(setup_script=setup_script)
        File "%TEMP%\pip-build-env-c8dy9cop\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 452, in <module>
        File "%TEMP%\pip-build-env-c8dy9cop\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "%TEMP%\pip-build-env-c8dy9cop\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "%TEMP%\pip-build-env-c8dy9cop\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "%TEMP%\pip-build-env-c8dy9cop\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "%TEMP%\pip-build-env-c8dy9cop\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "%TEMP%\pip-build-env-c8dy9cop\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "%TEMP%\pip-build-env-c8dy9cop\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 321, in run
          self.find_sources()
        File "%TEMP%\pip-build-env-c8dy9cop\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 329, in find_sources
          mm.run()
        File "%TEMP%\pip-build-env-c8dy9cop\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 550, in run
          self.add_defaults()
        File "%TEMP%\pip-build-env-c8dy9cop\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 595, in add_defaults
          self.read_manifest()
        File "%TEMP%\pip-build-env-c8dy9cop\overlay\Lib\site-packages\setuptools\command\sdist.py", line 203, in read_manifest
          self.filelist.append(line)
        File "%TEMP%\pip-build-env-c8dy9cop\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 487, in append
          path = convert_path(item)
                 ^^^^^^^^^^^^^^^^^^
        File "%TEMP%\pip-build-env-c8dy9cop\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 139, in convert_path
          raise ValueError("path '%s' cannot be absolute" % pathname)
      ValueError: path '/home/runner/work/lupa/lupa/third-party/lua52/lapi.c' cannot be absolute
```

**Comment by Godplayer-spec** [comment] 2024-02-19 04:57
I'm having the same error, I heard lupa wheel(s) doesn't support python 3.1.2 rn

**Comment by scoder** [comment] 2024-02-21 08:08
Duplicate of #245

**Closed by scoder** 2024-02-21 08:08 UTC
